services:
  rpc-proxy:
    image: ghcr.io/d8-x/d8x-rpc-proxy:main
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - CHAIN_ID=${CHAIN_ID}
      - RPC_CONFIG_FILE=${RPC_CONFIG_FILE}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - LISTEN_ADDR=${LISTEN_ADDR}
    volumes:
      - ./config/rpc-config.json:/config/rpc-config.json:ro
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
